services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: infra/docker/backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgresql
    ports:
      - "3001:3001"
    expose:
      - 3001
  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: infra/docker/frontend/Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    expose:
      - 3000

  postgresql:
    container_name: postgresql
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - $PWD/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432